### ISSUE TITLE
maybe wrong in A3C_RNN.py

### ISSUE THREAD

**Issue by ricky1203** [MorvanZhou/tutorials#37]
1. line 84/85 should be self.a_loss, self.c_loss
2. use the RNN state maybe wrong:
   a) mixed the RNN state in global network/local network
   b) update the local RNN state in line 160, but still update RNN hidden state with same observed state at line 146

**Comment by MorvanZhou** [comment]
Thanks.

1.  tf.gradients(ys, xs) this function will return _A list of `sum(dy/dx)` for each x in `xs`_, in other words, to accumulate gradient for every sample. So I use losses instead of loss.
2. Thank you, you are correct about the hidden state, I made a mistake in L118 about the state and I have fixed the hidden state passing issue. I added a rnn_state output when choosing action and modified code correspondingly.

The state exchange and passing should be fine now.
